- name: "Create kieadmin user with password test"
  lineinfile:
    path: "{{ wildlfy_users_file }}"
    regexp: "^kieadmin="
    line: "kieadmin=0a5c5e4d7023e4469ab0cb5c1a272723"

- name: "Assign roles to kieadmin user"
  lineinfile:
    path: "{{ wildlfy_roles_file }}"
    regexp: "^kieadmin="
    line: "kieadmin=admin,analyst,user,process-admin,kie-server"

- name: "Create kie server user with password kieserver1!"
  lineinfile:
    path: "{{ wildlfy_users_file }}"
    regexp: "^kieserver="
    line: "kieserver=16c6511893651c9b4b57e0c027a96075"

- name: "Assign roles to kieserver user"
  lineinfile:
    path: "{{ wildlfy_roles_file }}"
    regexp: "^kieserver="
    line: "kieserver=kie-server,rest-all"
