- import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: "Check that system-properties element exists in Wildfly config file"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:system-properties"
    namespaces:
      jd: "urn:jboss:domain:12.0"
    count: yes
  register: system_properties_hits
- name: "Add system-properties element to Wildfly config file"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:extensions"
    insertafter: yes
    pretty_print: yes
    namespaces:
      jd: "urn:jboss:domain:12.0"
    add_children:
    - "system-properties"
  when: system_properties_hits.count == 0
- name: "Add kie-server id system property"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:system-properties/jd:property[@name='org.kie.server.id' and @value='{{ kie_server_id }}']"
    pretty_print: yes
    namespaces:
      jd: "urn:jboss:domain:12.0"
  when: kie_server_id is defined
- name: "Add kie-server controller system property"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:system-properties/jd:property[@name='org.kie.server.controller' and @value='{{ kie_server_controller }}']"
    pretty_print: yes
    namespaces:
      jd: "urn:jboss:domain:12.0"
  when: kie_server_controller is defined
- name: "Add kie-server controller user system property"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:system-properties/jd:property[@name='org.kie.server.controller.user' and @value='{{ kie_server_controller_service_user }}']"
    pretty_print: yes
    namespaces:
      jd: "urn:jboss:domain:12.0"
  when: kie_server_controller_service_user is defined
- name: "Add kie-server controller password system property"
  xml:
    path: "{{ wildfly_config_file_path }}"
    xpath: "/jd:server/jd:system-properties/jd:property[@name='org.kie.server.controller.pwd' and @value='{{ kie_server_controller_service_password }}']"
    pretty_print: yes
    namespaces:
      jd: "urn:jboss:domain:12.0"
  when: kie_server_controller_service_password is defined
- name: "Restart Wildfly service"
  service:
    name: "{{ wildfly_service_name }}"
    state: "restarted"
  when: wildfly_service_name is defined

- name: Download Kie Server war
  get_url:
    url: "{{ kie_server_url }}"
    dest: "{{ wildfly_dest_dir }}/standalone/deployments/{{ kie_server_app_name }}.war"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
