redhat_tar_package_name: tar
redhat_update_package_cache: yes

wildfly_bootstrap_script: "{{ wildfly_dest_dir }}/bin/standalone.conf"
wildfly_config_file: "standalone-full.xml"
wildfly_config_file_path: "{{ wildfly_dest_dir }}/standalone/configuration/{{ wildfly_config_file }}"
wildfy_create_service: yes
wildfly_dest_dir: "/opt/wildfly"
wildfly_environment_file: "/etc/{{ wildfly_service_name }}/wildfly.conf"
wildfly_group: "wildfly"
wildfly_metaspace: "512M"
wildfly_metaspace_max: "8G"
wildfly_modify_memory_settings: yes
wildfly_service_file: "/etc/systemd/system/{{ wildfly_service_name }}.service"
wildfly_service_name: "wildfly"
wildfly_url: "https://download.jboss.org/wildfly/19.1.0.Final/wildfly-19.1.0.Final.tar.gz"
wildfly_user: "wildfly"
wildfly_xms: "256m"
wildfly_xmx: "2048m"
