- import_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Create user for Wildfly"
  user:
    name: "{{ wildfly_user }}"

- name: "Create group for Wildfly"
  group:
    name: "{{ wildfly_group }}"

- name: "Create directory for Wildfly"
  file:
    path: "{{ wildfly_dest_dir }}"
    state: directory
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"

- name: "Check if Wildfly folder is empty"
  find:
    path: "{{ wildfly_dest_dir }}"
  register: filesInWildflyDirFound

- name: "Download and unpack Wildfly"
  unarchive:
    src: "{{ wildfly_url }}"
    dest: "{{ wildfly_dest_dir }}"
    remote_src: yes
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    extra_opts: [--strip-components=1]
  when: filesInWildflyDirFound.matched == 0

- import_tasks: memory.yml
  when: wildfly_modify_memory_settings|default(false)|bool == true

- import_tasks: service.yml
  when: wildfy_create_service|default(false)|bool == true
